# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- feat/create-azurepipeline

pool:
  name: PoolRunners

stages:

# Stage 1: Install Node.js and Dependencies
- stage: Install
  displayName: 'Install Stage'
  jobs:
  - job: Install
    displayName: 'Install Node.js and Dependencies'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - task: Cache@2
      inputs:
        key: 'npm | "$(Agent.OS)" | package-lock.json'
        path: $(Build.SourcesDirectory)/node_modules
        cacheHitVar: CACHE_RESTORED
      displayName: 'Cache node_modules'

    - script: |
        npm ci
      displayName: 'Install dependencies'

    - script: |
        npm run lint
      displayName: 'Lint code'

    - script: |
        npm run build
        cp -R .next/* $(Build.ArtifactStagingDirectory)/
      displayName: 'Build and prepare artifacts'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: 'drop'
      displayName: 'Publish build artifacts'



