version: '3.8'

services:
  nextjsazuredevops:
    image: nextjsazuredevops-dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
