version: '3.8'

services:
  nextjsazuredevops:
    image: nextjsazuredevops
    build:
      context: .
      dockerfile: ./Dockerfile
      target: runner
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
